apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: sb-dfjdttutu44-cassandra
  name: sb-dfjdttutu44-cassandra
spec:
  replicas: 4
  selector:
      app: sb-dfjdttutu44-cassandra
  template:
    metadata:
      labels:
        app: sb-dfjdttutu44-cassandra
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            limits:
              cpu: 0.1
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SERVICE
              value: sb-dfjdttutu44-cassandra
            - name: cluster_name
              value: sb-dfjdttutu44-cassandra
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: 172.30.188.59:5000/yepeng/cassandra-openshift-orchestration:latest
          name: sb-dfjdttutu44-cassandra
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - /status_check.sh
      volumes:
        - name: data
          emptyDir: {}
